Remove 'go build' command

diff --git a/svbuild b/svbuild
--- a/svbuild
+++ b/svbuild
@@ -5,19 +5,17 @@ NEW_VER_LEVEL=3
 while getopts ":l:" opt; do
   case $opt in
     l) NEW_VER_LEVEL="$OPTARG" ;;
-    \?) echo "Invalid option -$OPTARG" >&2 ;;
+    \?) echo "Invalid option -$OPTARG" >&2 && exit 1 ;;
   esac
 done
 
-echo $NEW_VER_LEVEL
-
-#get highest tag number
 VERSION=`git describe --abbrev=0 --tags`
+if [ -z "$VERSION" ] ; then 
+    VERSION="0.0.0"
+fi
 
-#replace . with space so can split into an array
+# create new tag
 VERSION_BITS=(${VERSION//./ })
-
-#get number parts and increase last one by 1
 VNUM1=${VERSION_BITS[0]}
 VNUM2=${VERSION_BITS[1]}
 VNUM3=${VERSION_BITS[2]}
@@ -33,18 +31,20 @@ case $NEW_VER_LEVEL in
     ;;
 esac
 
-#create new tag
 NEW_TAG="$VNUM1.$VNUM2.$VNUM3"
-
-echo "Updating $VERSION to $NEW_TAG"
+echo "Updating $VERSION to $NEW_TAG" >&2
 
 #get current hash and see if it already has a tag
 GIT_COMMIT=`git rev-parse HEAD`
+if [ -z "$GIT_COMMIT" ] ; then
+    echo "Fatal: unknown git commit!" >&2
+    exit 2
+fi 
 NEEDS_TAG=`git describe --contains $GIT_COMMIT`
 
 #only tag if no tag already (would be better if the git describe command above could have a silent option)
 if [ -z "$NEEDS_TAG" ]; then
-    echo "Tagged with $NEW_TAG (Ignoring fatal:cannot describe - this means commit is untagged) "
+    echo "Tagged with $NEW_TAG (Ignoring fatal:cannot describe - this means commit is untagged) " >&2
     git tag $NEW_TAG
     git push --tags
 else
@@ -52,4 +52,4 @@ else
     echo "Already a tag on this commit - $NEW_TAG" >&2
 fi
 
-go build -ldflags "-X main.Version=$NEW_TAG"
+echo $NEW_TAG
